GET http://127.0.0.1:8000/test

###
GET http://127.0.0.1:8000/test/62c5960a64edba54a611bdca

###

POST http://127.0.0.1:8000/test
Content-Type: application/json

{
   
        "name": "tester"、
        "data": [
      {
        "title": "学ちか",
        "memoData":[
            {
                "length": 200,
                "text": "社会学のゼミで取り組んだ農村都市のPR活動のリーダーとしての仕事です。コロナ禍によりゼミ生との接点が少なくなりチームとしてやる気を無くしていました。そこで1週間に1度オンライン会議をおこない、PR活動の話だけではなく、個人の1週間の出来事を1分間で話す時間を設けました。結果以前よりもゼミ生同士の会話が増え、PR活動の取り組みもスムーズに進めることができました。"
            },
            {
                "length": 400,
                "text": "東南アジアの経済について学んでいる私は、地域間の教育格差へ問題意識を向け、プロジェクトへの参加を決意しました。プロジェクトリーダーを努め、様々な業種に携わる人々を小中学校に招き、自身の職業について講演、ワークショップを行うキャリアセミナーを提案しました。「講師の募集」「現地の小中学校の承諾を得ること」が最大の困難でした。この2点について、まず、講師の募集についてはターゲットを絞り込み自ら声掛けをすることでターゲット大学の学生を巻き込み50人以上の協力を得られました。また、小中学校の承諾を得るために、自ら足を動かし全15校の承諾を得られました。半年間に渡ったプロジェクトは、7日間で1,000人以上の小中学生が参加し想定以上の人数が参加してくれました。地元じゃない土地ではありましたが、主体性を活かしプロジェクトを達成した経験は困難な状況をチームワークで乗り越えることができる学びができました。"
            }
        ]
      },
      {
        "title": "企業選びの軸",
        "memoData":[
            {
                "length": 100,
                "text": "就活の軸を決めていても、実際に企業説明会に参加したり選考を受けたりする中で、当初の軸からブレてくることもあると思います"
            },
            {
                "length": 100,
                "text": "ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ"

            }
        ]
      }
    ]
  }

###
POST http://127.0.0.1:8000/test
Content-Type: application/json

{
    "name": "testeraa",
    "data": [
      {
        "title": "testaaaa"
      }
    ]
  }

###

DELETE  http://127.0.0.1:8000/test/62c5960e64edba54a611bdcc
Content-Type: application/json

###

PATCH  http://127.0.0.1:8000/test/62c5960a64edba54a611bdca
Content-Type: application/json

{
    "name": "tester",
    "data": [
      {
        "titel": "学ちかだよ",
        "memoData":[
            {
                "length": 210,
                "text": "社会学のゼミで取り組んだ農村都市のPR活動のリーダーとしての仕事です。コロナ禍によりゼミ生との接点が少なくなりチームとしてやる気を無くしていました。そこで1週間に1度オンライン会議をおこない、PR活動の話だけではなく、個人の1週間の出来事を1分間で話す時間を設けました。結果以前よりもゼミ生同士の会話が増え、PR活動の取り組みもスムーズに進めることができました。"
            },
            {
                "length": 400,
                "text": "東南アジアの経済について学んでいる私は、地域間の教育格差へ問題意識を向け、プロジェクトへの参加を決意しました。プロジェクトリーダーを努め、様々な業種に携わる人々を小中学校に招き、自身の職業について講演、ワークショップを行うキャリアセミナーを提案しました。「講師の募集」「現地の小中学校の承諾を得ること」が最大の困難でした。この2点について、まず、講師の募集についてはターゲットを絞り込み自ら声掛けをすることでターゲット大学の学生を巻き込み50人以上の協力を得られました。また、小中学校の承諾を得るために、自ら足を動かし全15校の承諾を得られました。半年間に渡ったプロジェクトは、7日間で1,000人以上の小中学生が参加し想定以上の人数が参加してくれました。地元じゃない土地ではありましたが、主体性を活かしプロジェクトを達成した経験は困難な状況をチームワークで乗り越えることができる学びができました。"
            }
        ]
      },
      {
        "titel": "企業選びの軸",
        "memoData":[
            {
                "length": 100,
                "text": "就活の軸を決めていても、実際に企業説明会に参加したり選考を受けたりする中で、当初の軸からブレてくることもあると思います"
            },
            {
                "length": 100,
                "text": "ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ"

            }
        ]
      }
    ]
  }

###

POST  http://127.0.0.1:8000/memo
Content-Type: application/json

{
    "data":[{
        "type":"userData",
        "name": "tester"
        },
    {
        "type":"memoData",
        "data": [
      {
        "titel": "学ちかだよ",
        "memoData":[
            {
                "length": 210,
                "text": "社会学のゼミで取り組んだ農村都市のPR活動のリーダーとしての仕事です。コロナ禍によりゼミ生との接点が少なくなりチームとしてやる気を無くしていました。そこで1週間に1度オンライン会議をおこない、PR活動の話だけではなく、個人の1週間の出来事を1分間で話す時間を設けました。結果以前よりもゼミ生同士の会話が増え、PR活動の取り組みもスムーズに進めることができました。"
            },
            {
                "length": 400,
                "text": "東南アジアの経済について学んでいる私は、地域間の教育格差へ問題意識を向け、プロジェクトへの参加を決意しました。プロジェクトリーダーを努め、様々な業種に携わる人々を小中学校に招き、自身の職業について講演、ワークショップを行うキャリアセミナーを提案しました。「講師の募集」「現地の小中学校の承諾を得ること」が最大の困難でした。この2点について、まず、講師の募集についてはターゲットを絞り込み自ら声掛けをすることでターゲット大学の学生を巻き込み50人以上の協力を得られました。また、小中学校の承諾を得るために、自ら足を動かし全15校の承諾を得られました。半年間に渡ったプロジェクトは、7日間で1,000人以上の小中学生が参加し想定以上の人数が参加してくれました。地元じゃない土地ではありましたが、主体性を活かしプロジェクトを達成した経験は困難な状況をチームワークで乗り越えることができる学びができました。"
            }
        ]
      },
      {
        "titel": "企業選びの軸",
        "memoData":[
            {
                "length": 100,
                "text": "就活の軸を決めていても、実際に企業説明会に参加したり選考を受けたりする中で、当初の軸からブレてくることもあると思います"
            },
            {
                "length": 100,
                "text": "ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ"

            }
        ]
      }
    ]}]
  }

